[workspace]
members=[
    "errors",
    "parser",
    "syntax",
    "semant",
    "tools",
    "tox",
]
default-members=["tox"]
[profile.dev.overrides."*"]
opt-level = 2
overflow-checks = true
debug-assertions = true
panic = "abort"
debug = false
codegen-units = 8
lto = false
incremental = true